from typing import List, Optional, Union
from pydantic import BaseModel, Field

class EvaluationInput(BaseModel):
    prompt: str = Field(..., description="The original prompt given to the LLM.")
    response: str = Field(..., description="The response generated by the LLM to be evaluated.")
    reference_answer: Optional[str] = Field(None, description="A gold standard reference answer.")
    context: Optional[str] = Field(None, description="The source context/EMR data for groundedness verification.")

class EvaluationResult(BaseModel):
    score: float = Field(..., description="The numerical score (e.g., 1-10 or 1-5).")
    reasoning: str = Field(..., description="The rationale behind the score (Chain-of-Thought).")
    criterion: str = Field(..., description="The criterion used for evaluation.")
    model_name: Optional[str] = Field(None, description="The name of the judge model used.")

class PairwiseInput(BaseModel):
    prompt: str
    response_a: str
    response_b: str
    reference_answer: Optional[str] = None
    context: Optional[str] = None

class PairwiseResult(BaseModel):
    winner: str = Field(..., description="The winner: 'A', 'B', or 'Tie'.")
    score_a: float = Field(..., description="Numerical score for Response A (1-5).")
    score_b: float = Field(..., description="Numerical score for Response B (1-5).")
    reasoning: str = Field(..., description="The rationale behind the decision.")
    model_name: Optional[str] = None

class Rubric(BaseModel):
    name: str
    description: str
    scoring_guide: dict[int, str]
    min_score: int = 1
    max_score: int = 5
